CREATE TABLE IF NOT EXISTS furnaces (
  uniqueID BIGINT PRIMARY KEY,
  ownerUUID BIGINT NOT NULL,
  worldName VARCHAR(255) NOT NULL,
  blockX INT NOT NULL,
  blockY INT NOT NULL,
  blockZ INT NOT NULL,
  active BOOL NOT NULL
);