CREATE TABLE IF NOT EXISTS worlds (
  uniqueID INT PRIMARY KEY,
  worldId VARCHAR(36) UNIQUE NOT NULL,
  firstSeen BIGINT NOT NULL,
  carbonValue MEDIUMINT NOT NULL,
  seaLevel TINYINT NOT NULL,
  size SMALLINT
);